var accountsPayload = [
  {
    "alias_ss": "", 
    "comp_partial_s": "", 
    "comp_website_s": "", 
    "company_address_line_1_t": "251 Church St", 
    "company_address_line_2_t": "", 
    "company_city_sst": "Naugatuck", 
    "company_country_sst": "United States", 
    "company_external_id_s": "194313480", 
    "company_revenue_l": 59433601, 
    "company_sst": "Ion Financial Mhc", 
    "company_state_sst": "CT", 
    "company_zipcode_sst": "06770-4121", 
    "created_at_dt": "2018-06-16T00:00:00.000Z", 
    "display_avk_id_s": "194313480", 
    "duplicate_company_s": "ion financial mhc", 
    "employees_lower_l": 200, 
    "employees_size_l": 250, 
    "employees_upper_l": 499, 
    "entity_type_s": "Parent", 
    "inactive_b": "", 
    "industry_sst": "Banking and Finance", 
    "internal_updated_at_dt": "", 
    "naics_description_sst": "Offices of Other Holding Companies", 
    "naics_sst": 551112, 
    "next_s": "", 
    "parent_company_external_s": "", 
    "phone_sst": "", 
    "previous_s": "", 
    "revenue_lower_l": 50000000, 
    "revenue_upper_l": 100000000, 
    "sic_description_sst": "Offices of Holding Companies, Not Elsewhere Classified", 
    "sic_sst": 6719, 
    "source_sst": "ACCOUNTMASTER", 
    "status_s": "QA", 
    "subindustry_sst": "Holding Companies", 
    "updated_at_dt": "2018-06-16T00:00:00.000Z", 
    "website_eml": "www.ionbank.com"
  }
];

module.exports = accountsPayload;