var contactsPayload = [
{
   "address_line_1_t": "83 Wooster Heights Rd",
   "address_line_2_t": "",
   "alias_ss": "",
   "city_sst": "Danbury",
   "company_revenue_l": 2921000000,
   "country_sst": "United States",
   "created_at_dt": "2018-12-10T00:00:00.000Z",
   "current_company_address_line_1_t": "83 Wooster Heights Rd",
   "current_company_address_line_2_t": "",
   "current_company_city_sst": "Danbury",
   "current_company_country_sst": "United States",
   "current_company_external_id_s": "194313480",
   "current_company_sst": "IMS Health Holdings, Inc.",
   "current_company_state_sst": "CT",
   "current_company_zipcode_sst": "06810",
   "current_department_sst": "Operations",
   "current_direct_phone_sst": "",
   "current_email_eml": "phinkle@imshealth.com",
   "current_employees_lower_l": 10000,
   "current_employees_upper_l": 5000000,
   "current_industry_sst": "Business and Management Services",
   "current_job_function_sst": "",
   "current_job_level_sst": "Manager",
   "current_naics_description_sst": "Offices of Other Holding Companies",
   "current_naics_sst": 551112,
   "current_phone_sst": "203-448-4600",
   "current_revenue_lower_l": 1000000000,
   "current_revenue_upper_l": 10000000000,
   "current_sic_description_sst": "Offices of Holding Companies, Not Elsewhere Classified",
   "current_sic_sst": 6719,
   "current_subindustry_sst": "Holding Companies",
   "current_title_sst": "Sr. Infosario Release Manager",
   "current_website_eml": "www.imshealth.com",
   "destination_tag_ss": "",
   "display_avk_id_s": "194313480",
   "email_domain_s": "imshealth.com",
   "email_pattern_s": 21.0,
   "employees_size_l": 15000,
   "error_code_s": "",
   "external_contact_id_s": "SNB62CM-000038471",
   "first_name_sst": "Phyllis",
   "fn_ln_comp_s": "phyllis|hinkle|ims health holdings, inc.",
   "fn_ln_email_domain_s": "phyllis|hinkle|imshealth.com",
   "fn_ln_phone_s": "phyllis|hinkle|203-448-4600",
   "gmail_bounce_date_dt": "",
   "gmail_bounce_status_s": "",
   "heat_index": "",
   "inactive_b": "",
   "internal_updated_at_dt": "2018-12-11T11:38:51.113Z",
   "last_name_sst": "Hinkle",
   "last_synced": "",
   "linkedin_url_eml": "",
   "next_s": "",
   "previous_s": "",
   "purchased_by_client_ss": "",
   "refreshed": "",
   "rl_job_function_ss": "",
   "source_sst": "SNMASTERDATA",
   "state_sst": "CT",
   "status_s": "QA",
   "updated_at_dt": "2018-12-10T00:00:00.000Z",
   "user_s": "",
   "zb_verification_date_dt": "2018-12-10T00:00:00.000Z",
   "zb_verification_status_s": "CatchAll",
   "zipcode_sst": "6810"
 },
 {
   "address_line_1_t": "83 Wooster Heights Rd",
   "address_line_2_t": "",
   "alias_ss": "",
   "city_sst": "Danbury",
   "company_revenue_l": 2921000000,
   "country_sst": "United States",
   "created_at_dt": "2018-12-10T00:00:00.000Z",
   "current_company_address_line_1_t": "83 Wooster Heights Rd",
   "current_company_address_line_2_t": "",
   "current_company_city_sst": "Danbury",
   "current_company_country_sst": "United States",
   "current_company_external_id_s": "194313480",
   "current_company_sst": "IMS Health Holdings, Inc.",
   "current_company_state_sst": "CT",
   "current_company_zipcode_sst": "06810",
   "current_department_sst": "Operations",
   "current_direct_phone_sst": "",
   "current_email_eml": "phinkle@imshealth.com",
   "current_employees_lower_l": 10000,
   "current_employees_upper_l": 5000000,
   "current_industry_sst": "Business and Management Services",
   "current_job_function_sst": "",
   "current_job_level_sst": "Manager",
   "current_naics_description_sst": "Offices of Other Holding Companies",
   "current_naics_sst": 551112,
   "current_phone_sst": "203-448-4600",
   "current_revenue_lower_l": 1000000000,
   "current_revenue_upper_l": 10000000000,
   "current_sic_description_sst": "Offices of Holding Companies, Not Elsewhere Classified",
   "current_sic_sst": 6719,
   "current_subindustry_sst": "Holding Companies",
   "current_title_sst": "Sr. Infosario Release Manager",
   "current_website_eml": "www.imshealth.com",
   "destination_tag_ss": "",
   "display_avk_id_s": "194313481",
   "email_domain_s": "imshealth.com",
   "email_pattern_s": 21.0,
   "employees_size_l": 15000,
   "error_code_s": "",
   "external_contact_id_s": "SNB62CM-000038472",
   "first_name_sst": "Phyllis",
   "fn_ln_comp_s": "phyllis|hinkle|ims health holdings, inc.",
   "fn_ln_email_domain_s": "phyllis|hinkle|imshealth.com",
   "fn_ln_phone_s": "phyllis|hinkle|203-448-4600",
   "gmail_bounce_date_dt": "",
   "gmail_bounce_status_s": "",
   "heat_index": "",
   "inactive_b": "",
   "internal_updated_at_dt": "2018-12-11T11:38:51.113Z",
   "last_name_sst": "Hinkle",
   "last_synced": "",
   "linkedin_url_eml": "",
   "next_s": "",
   "previous_s": "",
   "purchased_by_client_ss": "",
   "refreshed": "",
   "rl_job_function_ss": "",
   "source_sst": "SNMASTERDATA",
   "state_sst": "CT",
   "status_s": "QA",
   "updated_at_dt": "2018-12-10T00:00:00.000Z",
   "user_s": "",
   "zb_verification_date_dt": "2018-12-10T00:00:00.000Z",
   "zb_verification_status_s": "CatchAll",
   "zipcode_sst": "6810"
 },
 {
   "address_line_1_t": "83 Wooster Heights Rd",
   "address_line_2_t": "",
   "alias_ss": "",
   "city_sst": "Danbury",
   "company_revenue_l": 2921000000,
   "country_sst": "United States",
   "created_at_dt": "2018-12-10T00:00:00.000Z",
   "current_company_address_line_1_t": "83 Wooster Heights Rd",
   "current_company_address_line_2_t": "",
   "current_company_city_sst": "Danbury",
   "current_company_country_sst": "United States",
   "current_company_external_id_s": "194313480",
   "current_company_sst": "IMS Health Holdings, Inc.",
   "current_company_state_sst": "CT",
   "current_company_zipcode_sst": "06810",
   "current_department_sst": "Operations",
   "current_direct_phone_sst": "",
   "current_email_eml": "phinkle@imshealth.com",
   "current_employees_lower_l": 10000,
   "current_employees_upper_l": 5000000,
   "current_industry_sst": "Business and Management Services",
   "current_job_function_sst": "",
   "current_job_level_sst": "Manager",
   "current_naics_description_sst": "Offices of Other Holding Companies",
   "current_naics_sst": 551112,
   "current_phone_sst": "203-448-4600",
   "current_revenue_lower_l": 1000000000,
   "current_revenue_upper_l": 10000000000,
   "current_sic_description_sst": "Offices of Holding Companies, Not Elsewhere Classified",
   "current_sic_sst": 6719,
   "current_subindustry_sst": "Holding Companies",
   "current_title_sst": "Sr. Infosario Release Manager",
   "current_website_eml": "www.imshealth.com",
   "destination_tag_ss": "",
   "display_avk_id_s": "194313480",
   "email_domain_s": "imshealth.com",
   "email_pattern_s": 21.0,
   "employees_size_l": 15000,
   "error_code_s": "",
   "external_contact_id_s": "SNB62CM-000038474",
   "first_name_sst": "Phyllis",
   "fn_ln_comp_s": "phyllis|hinkle|ims health holdings, inc.",
   "fn_ln_email_domain_s": "phyllis|hinkle|imshealth.com",
   "fn_ln_phone_s": "phyllis|hinkle|203-448-4600",
   "gmail_bounce_date_dt": "",
   "gmail_bounce_status_s": "",
   "heat_index": "",
   "inactive_b": "",
   "internal_updated_at_dt": "2018-12-11T11:38:51.113Z",
   "last_name_sst": "Hinkle",
   "last_synced": "",
   "linkedin_url_eml": "",
   "next_s": "",
   "previous_s": "",
   "purchased_by_client_ss": "",
   "refreshed": "",
   "rl_job_function_ss": "",
   "source_sst": "SNMASTERDATA",
   "state_sst": "CT",
   "status_s": "QA",
   "updated_at_dt": "2018-12-10T00:00:00.000Z",
   "user_s": "",
   "zb_verification_date_dt": "2018-12-10T00:00:00.000Z",
   "zb_verification_status_s": "CatchAll",
   "zipcode_sst": "6810"
 },
];

module.exports = contactsPayload;